#include "adc.h"


AdcChannelGroup ArrayOfAdcChannelGroups[MAX_NB_GROUPS] = {
{
0,    //ID
ADC0,
SS0, 
ADC_TRIG_SRC_HW, 
ADC_TRIG_TIMER,
ADC_HW_TRIG_RISING_EDGE, 
ADC_CONV_MODE_CONTINUOUS,
ADC_ACCESS_MODE_SINGLE,
ADC_STREAM_BUFFER_LINEAR,
0,   //Priority
2,   //Nb of channels
{PE3,PD2} 
}
//{ADC0, SS1, ADC_TRIGGER_TIMER, 1, {PD2} }
};
